let languageArr=[
    {contry:'Afrikaans ' , code:'af'},
    {contry:'Basque  ' , code:'eu'},
    {contry:'Bulgarian   ' , code:'bg'},
    {contry:'Catalan    ' , code:'ca'},
    {contry:'Arabic (Egypt) ' , code:'ar-EG'},
    {contry:'Arabic (Jordan)' , code:'ar-JO'},
    {contry:'Arabic (Kuwait)     ' , code:'ar-KW'},
    {contry:'Arabic (Lebanon) ' , code:'ar-LB'},
    {contry:'Arabic (Qatar)' , code:'ar-QA'},
    {contry:'Arabic (UAE)' , code:'ar-AE'},
    {contry:'Arabic (Morocco) ' , code:'ar-MA'},
    {contry:'Arabic (Iraq)' , code:'ar-IQ'},
    {contry:'Arabic (Algeria)' , code:'ar-DZ'},
    {contry:'Arabic (Bahrain)' , code:'ar-BH'},
    {contry:'Arabic (Lybia)' , code:'ar-LY'},
    {contry:'Arabic (Oman)' , code:'ar-OM'},
    {contry:'Arabic (Saudi Arabia) ' , code:'ar-SA'},
    {contry:'Arabic (Tunisia)' , code:'ar-TN'},
    {contry:'Arabic (Yemen)' , code:'ar-YE'},
    {contry:'Czech' , code:'cs'},
    {contry:'Dutch' , code:'nl-NL'},
    {contry:'English (Australia)' , code:'en-AU'},
    {contry:'English (Canada)' , code:'en-CA'},
    {contry:'English (India)' , code:'en-IN'},
    {contry:'English (New Zealand)' , code:'en-NZ'},
    {contry:'English (South Africa) ' , code:'en-ZA'},
    {contry:'English(UK)' , code:'en-GB'},
    {contry:'English(US)' , code:'en-US'},
    {contry:'Finnish' , code:'fi'},
    {contry:'French ' , code:'fr-FR'},
    {contry:'Galician ' , code:'gl'},
    {contry:'German  ' , code:'de-DE'},
    {contry:'Greek  ' , code:'el-GR'},
    {contry:'Hebrew  ' , code:'he'},
    {contry:'Hungarian   ' , code:'hu'},
    {contry:'Icelandic    ' , code:'is'},
    {contry:'Italian     ' , code:'it-IT'},
    {contry:'Indonesian     ' , code:'id'},
    {contry:'Japanese' , code:'ja'},
    {contry:'Korean ' , code:'ko'},
    {contry:'Latin  ' , code:'la'},
    {contry:'Mandarin Chinese  ' , code:'zh-CN'},
    {contry:'Taiwanese   ' , code:'zh-TW'},
    {contry:'Cantonese' , code:'zh-HK'},
    {contry:'Malaysian ' , code:'ms-MY'},
    {contry:'Norwegian  ' , code:'no-NO'},
    {contry:'Polish   ' , code:'pl'},
    {contry:'Pig Latin   ' , code:'xx-piglatin'},
    {contry:'Portuguese' , code:'pt-PT'},
    {contry:'Portuguese (Brasil)' , code:'pt-br'},
    {contry:'Romanian    ' , code:'ro-RO'},
    {contry:'Russian   ' , code:'ru'},
    {contry:'Serbian    ' , code:'sr-SP'},
    {contry:'Slovak' , code:'sk'},
    {contry:'Spanish (Argentina)' , code:'es-AR'},
    {contry:'SlSpanish (Bolivia)' , code:'es-BO'},
    {contry:'Spanish (Chile) ' , code:'es-CL'},
    {contry:'Spanish (Colombia)' , code:'es-CO'},
    {contry:'Spanish (Costa Rica)' , code:'es-CR'},
    {contry:'Spanish (Dominican Republic)' , code:'es-DO'},
    {contry:'Spanish (Ecuador)' , code:'es-EC'},
    {contry:'Spanish (El Salvador)' , code:'es-SV'},
    {contry:'Spanish (Guatemala)' , code:'es-GT'},
    {contry:'Spanish (Honduras) ' , code:'es-HN'},
    {contry:'Spanish (Mexico)' , code:'es-MX'},
    {contry:'Spanish (Nicaragua) ' , code:'es-NI'},
    {contry:'Spanish (Panama)' , code:'es-PA'},
    {contry:'Spanish (Paraguay)' , code:'es-PY'},
    {contry:'Spanish (Peru) ' , code:'es-PE'},
    {contry:'Spanish (Puerto Rico) ' , code:'es-PR'},
    {contry:'Spanish (Spain)' , code:'es-ES'},
    {contry:'Spanish (US)' , code:'es-US'},
    {contry:'Spanish (Uruguay)' , code:'es-UY'},
    {contry:'Spanish (Venezuela) ' , code:'es-VE'},
    {contry:'Swedish ' , code:'sv-SE'},
    {contry:'Turkish ' , code:'tr'},
    {contry:'Zulu  ' , code:'zu'},

]
export default languageArr;